// DO NOT EDIT : This file is generated by chevron
/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// presto_protocol.prolog.cpp
//

// This file is generated DO NOT EDIT @generated

#include <iostream>

#include "presto_cpp/presto_protocol/connector/denodo_arrow/presto_protocol_denodo_arrow.h"
using namespace std::string_literals;

// ArrowTransactionHandle is special since
// the corresponding class in Java is an enum.

namespace facebook::presto::protocol::denodo_arrow {

void to_json(json& j, const ArrowTransactionHandle& p) {
  j = json::array();
  j.push_back(p._type);
  j.push_back(p.instance);
}

void from_json(const json& j, ArrowTransactionHandle& p) {
  j[0].get_to(p._type);
  j[1].get_to(p.instance);
}
} // namespace facebook::presto::protocol::denodo_arrow
namespace facebook::presto::protocol::denodo_arrow {
ArrowColumnHandle::ArrowColumnHandle() noexcept {
  _type = "denodo-arrow";
}

void to_json(json& j, const ArrowColumnHandle& p) {
  j = json::object();
  j["@type"] = "denodo-arrow";
  to_json_key(
      j,
      "columnName",
      p.columnName,
      "ArrowColumnHandle",
      "String",
      "columnName");
  to_json_key(
      j, "columnType", p.columnType, "ArrowColumnHandle", "Type", "columnType");
}

void from_json(const json& j, ArrowColumnHandle& p) {
  p._type = j["@type"];
  from_json_key(
      j,
      "columnName",
      p.columnName,
      "ArrowColumnHandle",
      "String",
      "columnName");
  from_json_key(
      j, "columnType", p.columnType, "ArrowColumnHandle", "Type", "columnType");
}
} // namespace facebook::presto::protocol::denodo_arrow
namespace facebook::presto::protocol::denodo_arrow {
ArrowTableHandle::ArrowTableHandle() noexcept {
  _type = "denodo-arrow";
}

void to_json(json& j, const ArrowTableHandle& p) {
  j = json::object();
  j["@type"] = "denodo-arrow";
  to_json_key(j, "schema", p.schema, "ArrowTableHandle", "String", "schema");
  to_json_key(j, "table", p.table, "ArrowTableHandle", "String", "table");
}

void from_json(const json& j, ArrowTableHandle& p) {
  p._type = j["@type"];
  from_json_key(j, "schema", p.schema, "ArrowTableHandle", "String", "schema");
  from_json_key(j, "table", p.table, "ArrowTableHandle", "String", "table");
}
} // namespace facebook::presto::protocol::denodo_arrow
namespace facebook::presto::protocol::denodo_arrow {
void to_json(json& j, const std::shared_ptr<ColumnHandle>& p) {
  if (p == nullptr) {
    return;
  }
  String type = p->_type;

  if (type == "denodo-arrow") {
    j = *std::static_pointer_cast<ArrowColumnHandle>(p);
    return;
  }

  throw TypeError(type + " no abstract type ColumnHandle ");
}

void from_json(const json& j, std::shared_ptr<ColumnHandle>& p) {
  String type;
  try {
    type = p->getSubclassKey(j);
  } catch (json::parse_error& e) {
    throw ParseError(std::string(e.what()) + " ColumnHandle  ColumnHandle");
  }

  if (type == "denodo-arrow") {
    std::shared_ptr<ArrowColumnHandle> k =
        std::make_shared<ArrowColumnHandle>();
    j.get_to(*k);
    p = std::static_pointer_cast<ColumnHandle>(k);
    return;
  }

  throw TypeError(type + " no abstract type ColumnHandle ");
}
} // namespace facebook::presto::protocol::denodo_arrow
namespace facebook::presto::protocol::denodo_arrow {
ArrowTableLayoutHandle::ArrowTableLayoutHandle() noexcept {
  _type = "denodo-arrow";
}

void to_json(json& j, const ArrowTableLayoutHandle& p) {
  j = json::object();
  j["@type"] = "denodo-arrow";
  to_json_key(
      j,
      "table",
      p.table,
      "ArrowTableLayoutHandle",
      "ArrowTableHandle",
      "table");
  to_json_key(
      j,
      "columnHandles",
      p.columnHandles,
      "ArrowTableLayoutHandle",
      "List<ArrowColumnHandle>",
      "columnHandles");
  to_json_key(
      j,
      "tupleDomain",
      p.tupleDomain,
      "ArrowTableLayoutHandle",
      "TupleDomain<std::shared_ptr<ColumnHandle>>",
      "tupleDomain");
}

void from_json(const json& j, ArrowTableLayoutHandle& p) {
  p._type = j["@type"];
  from_json_key(
      j,
      "table",
      p.table,
      "ArrowTableLayoutHandle",
      "ArrowTableHandle",
      "table");
  from_json_key(
      j,
      "columnHandles",
      p.columnHandles,
      "ArrowTableLayoutHandle",
      "List<ArrowColumnHandle>",
      "columnHandles");
  from_json_key(
      j,
      "tupleDomain",
      p.tupleDomain,
      "ArrowTableLayoutHandle",
      "TupleDomain<std::shared_ptr<ColumnHandle>>",
      "tupleDomain");
}
} // namespace facebook::presto::protocol::denodo_arrow
namespace facebook::presto::protocol::denodo_arrow {
DenodoArrowSplit::DenodoArrowSplit() noexcept {
  _type = "denodo-arrow";
}

void to_json(json& j, const DenodoArrowSplit& p) {
  j = json::object();
  j["@type"] = "denodo-arrow";
  to_json_key(
      j,
      "schemaName",
      p.schemaName,
      "DenodoArrowSplit",
      "String",
      "schemaName");
  to_json_key(
      j, "tableName", p.tableName, "DenodoArrowSplit", "String", "tableName");
  to_json_key(
      j,
      "flightEndpointBytes",
      p.flightEndpointBytes,
      "DenodoArrowSplit",
      "String",
      "flightEndpointBytes");
  to_json_key(
      j,
      "executionIdentifier",
      p.executionIdentifier,
      "DenodoArrowSplit",
      "String",
      "executionIdentifier");
}

void from_json(const json& j, DenodoArrowSplit& p) {
  p._type = j["@type"];
  from_json_key(
      j,
      "schemaName",
      p.schemaName,
      "DenodoArrowSplit",
      "String",
      "schemaName");
  from_json_key(
      j, "tableName", p.tableName, "DenodoArrowSplit", "String", "tableName");
  from_json_key(
      j,
      "flightEndpointBytes",
      p.flightEndpointBytes,
      "DenodoArrowSplit",
      "String",
      "flightEndpointBytes");
  from_json_key(
      j,
      "executionIdentifier",
      p.executionIdentifier,
      "DenodoArrowSplit",
      "String",
      "executionIdentifier");
}
} // namespace facebook::presto::protocol::denodo_arrow
